services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile_server
    container_name: server1
    environment:
      - PORT=8000
      - SERVER_NAME=server1
    ports:
      - "8001:8000"

  server2:
    build:
      context: .
      dockerfile: Dockerfile_server
    container_name: server2
    environment:
      - PORT=8000
      - SERVER_NAME=server2
    ports:
      - "8002:8000"

  server3:
    build:
      context: .
      dockerfile: Dockerfile_server
    container_name: server3
    environment:
      - PORT=8000
      - SERVER_NAME=server3
    ports:
      - "8003:8000"

  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: load_balancer
    depends_on:
      - server1
      - server2
      - server3
    ports:
      - "8080:8080"
    environment:
      - SERVERS=http://server1:8000,http://server2:8000,http://server3:8000